[package]
name = "pattern-3"
version = "0.1.0"
authors = ["kennytm <kennytm@gmail.com>"]

[dependencies]
memchr = "*"
libc = "*"

# [dev-dependencies]
# regex = "*"

[profile.release]
panic = "abort"
